# Generated by SqlRustler at 2025-11-27 00:43:45
from sqlrustler.field import *
from sqlrustler.migrations.operations import *

dependencies = []

operations = [
    CreateTable(name='post', fields={
            'id': IntegerField(primary_key=True),
            'title': CharField(max_length=200),
            'content': CharField(max_length=1000),
        }),
    CreateTable(name='user', fields={
            'id': IntegerField(primary_key=True),
            'username': CharField(max_length=50),
            'email': CharField(max_length=100),
        }),
]
