"""
Migration file writer.
"""
import os
import time
from typing import List
from .operations import Operation

class MigrationWriter:
    def __init__(self, migration_name: str, operations: List[Operation], dependencies: List[str] = None):
        self.migration_name = migration_name
        self.operations = operations
        self.dependencies = dependencies or []

    def as_string(self) -> str:
        imports = set()
        imports.add("from sqlrustler.migrations.operations import *")
        imports.add("from sqlrustler.field import *")
        
        ops_str = "[\n"
        for op in self.operations:
            if hasattr(op, 'fields'):
                # CreateTable
                fields_str = "{\n"
                for name, field in op.fields.items():
                    # This is a simplification. Serializing fields properly requires more work.
                    # We'll use a basic repr for now.
                    # Ideally we need a deconstruct method on Field.
                    field_repr = self._serialize_field(field)
                    fields_str += f"            '{name}': {field_repr},\n"
                fields_str += "        }"
                ops_str += f"    CreateTable(name='{op.name}', fields={fields_str}),\n"
            else:
                # Other operations
                pass # TODO: Implement other ops serialization
        ops_str += "]"

        return f"""# Generated by SqlRustler at {time.strftime('%Y-%m-%d %H:%M:%S')}
{chr(10).join(imports)}

dependencies = {self.dependencies}

operations = {ops_str}
"""

    def _serialize_field(self, field) -> str:
        # Basic serialization
        cls_name = field.__class__.__name__
        params = []
        if field.primary_key: params.append("primary_key=True")
        if not field.null: params.append("null=False")
        if field.default is not None: params.append(f"default={repr(field.default)}")
        if hasattr(field, 'max_length') and field.max_length: params.append(f"max_length={field.max_length}")
        
        return f"{cls_name}({', '.join(params)})"
